### ISSUE TITLE
More context on oCat

### ISSUE THREAD

**Issue by bytemare** [cfrg/draft-irtf-cfrg-cpace#6] opened 2022-01-07 22:39 UTC
The `oCat` function could benefit from some explanation of what the ordering is. The POC uses Python's ">" operator, which is lexicographical ordering, using the Unicode code point number to order individual characters. This might not be super clear to the reader.

Besides, what's the reason for that ordering?

**Comment by BjoernMHaase** [comment] 2022-01-08 10:05
Hello "bytemare",

thank you for your feedback. I agree with you, in that the specification benefits from a more information on the octet string comparison.

I have just pushed a revised version of the draft to the repo. Specifically, I have replaced the variable names str1,str2 with bytes1, bytes2 in order to make clear that it's not a unicode python string that is compared but a plain octet string.

Secondly I have added an explicit comparison function implementation (that matches the python spec.).

I would appreciate your feedback on my suggested fix and would close the issue and upload a new draft revision if you think that the issue is resolved.

Thank you again!

**Comment by BjoernMHaase** [comment] 2022-01-08 10:07
BTW: 
"Besides, what's the reason for that ordering?":

We considered that lexiographical ordering of bytes would be the simplest straight-forward approach to use if both parties use the symmetric setting where no message-sequencing is enforced. Do you actually have a suggestion on how to implement that even more simple?

**Comment by BjoernMHaase** [comment] 2022-01-08 10:36
Salut, Daniel,Merci pour regarder le draft de CPace.Je viens de laisser des reponses sur les issues chez github (je ne sais pas, si github t'a aussi deja averti.),Björn.--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 07.01.22, 23:40 schrieb Daniel Bourdrez ***@***.***>:

   
  The oCat function could benefit from some explanation of what the ordering is. The POC uses Python's ">" operator, which is lexicographical ordering, using the Unicode code point number to order individual characters. This might not be super clear to the reader. 
  Besides, what's the reason for that ordering?

**Comment by bytemare** [comment] 2022-01-08 15:29
Vielen Dank Björn 😃 Ja, auf Github antworten reicht 😉

**Comment by bytemare** [comment] 2022-01-08 15:59
The new description is abundantly clear, thank you very much! I'm not sure this is worth a new version, though, as this is simply editorial and doesn't change the spec :)

For the ordering, the most straightforward concatenation to me is to keep it simple: since oCat is only used in one place and to concatenate msgA and msgB, I think it's more interesting to just keep that order, i.e. `oCat(msgA, msgB) = length_prefixed(msgA) || length_prefixed(msgB)`.
You mentioned

> the symmetric setting where no message-sequencing is enforced

When does that happen? Doesn't msgA (initiator) always come before msgB (responder)?

**Comment by BjoernMHaase** [comment] 2022-01-08 17:43
In the symmetric setting there is indeed no ordering. Both, party A or party B might come first. That's for instance the case in the "magic wormhole" use case. That's why it's unclear in the symmetric case for both parties which message needs to go first in the transcript. The oCat procedure resolves this issue.--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.

**Comment by BjoernMHaase** [comment] 2022-01-09 13:02
I just pushed corresponding fixes.

**Closed as completed by BjoernMHaase** 2022-01-09 13:02 UTC

**Comment by bytemare** [comment] 2022-01-09 14:14
Very clear! I missed the fact there could be different settings. Hence, I agree this method might be the most straightforward way to go with.
